version: '3.4'

services:
  dockerkubelearn:
    image: dockerkubelearn
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
